name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Install dependencies
      run: |
        # sudo gem install cocoapods
        # pod install

    - name: Build with xcodebuild
      run: |
        xcodebuild clean build \
          -project AirBar.xcodeproj \
          -scheme AirBar \
          -sdk macosx \
          -arch arm64 \ 
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CONFIGURATION_BUILD_DIR=$(pwd)/build/Release

    - name: List build directory for debugging
      run: ls -la build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AirBar
        path: build
