name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2' # 选择你需要的 Xcode 版本

    - name: Install dependencies
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build with xcodebuild
      run: |
        xcodebuild clean build \
          -project AirBar.xcodeproj \
          -scheme AirBar \
          -sdk macosx \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: AirBar
        path: build/Release/AirBar.app
