name: macOS CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: ${{ runner.os }}-xcode-${{ hashFiles('**/Package.resolved') }}

      - name: Import Certificates
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Build and Archive
        run: |
          xcodebuild -scheme "AirBar" \
                     -configuration Release \
                     -archivePath "AirBar.xcarchive" \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath "AirBar.xcarchive" \
                     -exportOptionsPlist "ExportOptions.plist" \
                     -exportPath "build"

      - name: Notarize Application
        uses: Apple-Actions/notarize-app@v1
        with:
          app-path: "build/AirBar.app"
          apple-id: ${{ secrets.APPLE_ID }}
          password: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/AirBar.app.zip
