name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Install dependencies (if needed)
      run: |
        # sudo gem install cocoapods
        # pod install

    - name: Build with xcodebuild
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: |
        xcodebuild clean build \
          -project AirBar.xcodeproj \
          -scheme AirBar \
          -sdk macosx \
          -arch arm64 \
          -configuration Release \
          -allowProvisioningUpdates \
          CODE_SIGN_IDENTITY="Apple Development" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=$TEAM_ID \
          CODE_SIGN_STYLE=Automatic \
          CONFIGURATION_BUILD_DIR=$(pwd)/build/Release

    - name: List build directory for debugging
      run: ls -la build/Release

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AirBar
        path: build/Release/AirBar.app
